services:
  web:
    image: registry.digitalocean.com/image-register/go-sample-app:b486188d2b2747843037ef8584c497dc7317493d
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - my-network

  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network

networks:
  my-network:
    driver: bridge