services:
  web:
    image: go-sample-app
    restart: unless-stopped
    expose:
      - "5000"

  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web