version: "3.8"

services:
  web:
    image: go-sample-app
    restart: unless-stopped
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_healthy